apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafkaesk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafkaesk
    spec:
      containers:
        - name: kafkaesk-server
          image: gcr.io/citric-lead-197512/kafkaesk:v1
          command: [ "/bin/sh", "-c", "ls /config" ]
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: gcp-sa-credentials
---
kind: Service
apiVersion: v1
metadata:
  name: kafkaesk-srv
spec:
  type: NodePort
  selector:
    app: kafkaesk
  ports:
  - protocol: TCP
    port: 80