swagger: "2.0"
info:
  version: "0.0.1"
  title: Event handler
host: localhost:10010
basePath: /kafkaesk/v1/api
#
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /event:
    x-swagger-router-controller: event
    post:
      description: Instantiates a new event
      operationId: eventCreate
      parameters:
        - name: event
          in: body
          required: true
          schema:
            $ref: "#/definitions/Event"
      responses:
        "201":
          description: Created
          schema:
            $ref: "#/definitions/Event"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  Event:
    required:
      - message
      - eventSpec
      - topic
    properties:
      id:
        type: string
      topic:
        type: string
      eventSpec:
        type: string
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
